public inherited sharing class CalloutConstants {

    public static final String APPLICATIONSLASHJSON = 'application/json;';
    public static final String CALLOUTCOLON = 'callout:';
    public static final Integer CALLOUTIMEOUT = 120000;
    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String CLIENT_ID = 'client_id';
    public static final String CLIENT_SECRET = 'client_secret';
    public static final String CREDENTIAL_USERNAMEMERGEFIELD = '{!$Credential.UserName}';
    public static final String CREDENTIAL_PWDMERGEFIELD = '{!$Credential.Password}';
    public static final String FAILURE ='Failure';
    public static final Integer FOURHUNDRED = 400;
    public static final String GET = 'GET';
    public static final String JNJ101 = 'JNJ101';
    public static final String JNJ007 = 'JNJ007';
    public static final String NAEREGION ='North America';
    public static final String POST = 'POST';
    public static final String PUT = 'PUT';
    public static final String RESPONSE = 'Response';
    public static final String RETRY = 'Retry';
    public static final String SUCCESS = 'Success';
    public static final Integer TWO_HUNDRED_AND_ONE = 201;
    public static final Integer TWOHUNDRED = 200;
}
