public class StaticConstants
{
	public static final String accountRole { get { return 'AccountRole'; } }
	public static final String APHERESISSITE { get { return 'ApheresisSite'; } } 
	public static final String APHERESISSITELABEL { get { return 'Apheresis Site'; } }
	public static final String apheresisPickupConfirmedStatus { get { return 'Apheresis Pickup Date Scheduled'; } }
	public static final String apheresisPickupRequestedStatus { get { return 'Apheresis Pickup Date Requested'; } }
    public static final String apheresisPOReceived { get { return 'Aph PO Received'; } }
	public static final String BLANKVALUE { get { return ' '; } }
	public static final String CaregiverRecordTypeDeveloperName { get { return 'Caregiver'; } }
	public static final String CarePlanRecordTypeDeveloperName { get { return 'CarePlan'; } }
	public static final String carePlanStatusAsNew { get { return 'New'; } }
	public static final String carePlanStatusAsApheresed { get { return 'Apheresed'; } }
	public static final String carePlanStatusAsDrugProductShipped { get { return 'Drug Product Shipped'; } }
    public static final String carePlanStatusAsInfused { get { return 'Infused'; } }
	public static final String CARTCOORDINATOR { get { return 'CAR-T Coordinator'; } }
	public static final String COMMA { get { return ','; } }
	public static final String COLON { get { return ':'; } }
	public static final String completedStatus { get { return 'Completed'; } }
	public static final String contactContactRelation { get { return 'Contact Contact Relation'; } }
	public static final String contactRole { get { return 'ContactRole'; } }
	public static final String cryoCellsDelivered { get { return 'Cryo-ed Cells Delivered'; } }
	public static final String CryoSiteCentral { get { return 'Central'; } }
	public static final String drugProductDelivered { get { return 'Drug Product Delivered'; } }
	public static final String CRYOSITE { get { return 'CryoSite'; } }
	public static final String CRYOSITELABEL { get { return 'Cryo Site'; } }
	public static final String cryoSiteLocal { get { return 'Local'; } }
	public static final String cryoTypeRaritan { get { return 'Raritan'; } }
	public static final String deliveryOfFinalProductToInfusionTreatmentSite { get { return 'Confirmation on delivery of final product to the Infusion/ Treatment Site';} }
	public static final String freshCellsDelivered { get { return 'Fresh Cells Delivered'; } }
	public static final String finalProductDelivered { get { return 'Drug Product Delivered'; } }
	public static final String goalName { get { return 'Shipping (Apheresis Site to Cryo Site)'; } }
	public static final String hardSlotReserved { get { return 'Slot Confirmed'; } }
	public static final String inProgressStatus { get { return 'In Progress'; } }
	public static final String MANUFACTURING { get { return 'Manufacturing'; } }
	public static final String manufacturingComplete { get { return 'Manufacturing Complete'; } }
	public static final String manufacturingNotStarted { get { return 'Not Started'; } }
	public static final String manufacturingSiteRecTypeDeveloperName { get { return 'ManufacturingSite'; } }
	public static final String MANUFACTURING_STARTED { get { return 'Manufacturing Started'; } }
	public static final String NAMELABEL { get { return 'Name'; } }
    public static final String orderInfusionComplete { get { return 'Infusion Complete'; } }
	public static final String orderInProgress { get { return 'Order In Progress'; } }
	public static final String orderInProgressStatus { get { return 'Order In Progress'; } }
	public static final String orderPlacement { get { return 'Order Placement'; } }
    public static final String OrderRescheduled { get { return 'Order Rescheduled'; } }
	public static final String orderSubmitted { get { return 'Order Submitted'; } }
	public static final String orderVerified { get { return 'Order Verified'; } }
	public static final String PatientRecordTypeDeveloperName { get { return 'Patient'; } }
	public static final String POPending { get { return 'PO Pending'; } }
	public static final String POReceived { get { return 'PO Received'; } }
	public static final String PatientStatusVerified { get { return 'Verified'; } }
	public static final String QC_QA_COMPLETE { get { return 'QC/QA Complete'; } }
	public static final String QRCOMPLETED { get { return 'QR Complete'; } }
    public static final String RECORDINFUSIONDATE { get { return 'Record Infusion Date'; } }
	public static final String REQUESTPAYLOAD { get { return ' Request Payload : '; } }
	public static final String REQUESTTYPENEW { get { return 'New'; } }
	public static final String REQUESTTYPERESCHEDULED { get { return 'Rescheduled'; } }
	public static final String shippingFinalProduct { get { return 'Shipping Drug Product'; } }
	public static final String shippingFreshCells { get { return 'Shipping Fresh Cells'; } }
	public static final String shippingCryoCells { get { return 'Shipping Cryo-ed Cells'; } }
	public static final String SLOTBOOKING { get { return 'Slot Booking'; } }
	public static final String softSlotConfirmed { get { return 'Slot Confirmed'; } }
	public static final String softSlotRequested { get { return 'Slot Requested'; } }
	public static final String SUBJECTLABEL { get { return 'Subject'; } }
	public static final String TRANSACTIONNAME { get { return 'Transaction Name : '; } }
	public static final String TreatmentSiteRecordTypeDeveloperName { get { return 'TreatmentSite'; } }
	public static final String TREATMENTSITELABEL { get { return 'Treatment Site'; } }

}